# Generated by Django 5.2.8 on 2025-11-18 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('entrance', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('intercom', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('09-11', '09:00–11:00'), ('11-13', '11:00–13:00'), ('13-15', '13:00–15:00'), ('15-17', '15:00–17:00'), ('17-19', '17:00–19:00'), ('19-21', '19:00–21:00')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('taken', 'Назначен'), ('en_route', 'В пути'), ('done', 'Выполнен'), ('canceled', 'Отменён'), ('failed', 'Не удалось'), ('overdue', 'Просрочен')], default='new', max_length=20)),
                ('payment_reserved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meta.district')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_user_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
